apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openhab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourname/oh-expose.git
    targetRevision: HEAD
    path: microk8s/charts/openhab-stack
    helm:
      releaseName: openhab-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
