---
tunnel: YOUR-KEYCLOAK-TUNNEL-ID
credentials-file: /etc/cloudflared/YOUR-KEYCLOAK-TUNNEL-ID.json

ingress:
  - hostname: keycloak.cjssolutions.com
    service: http://keycloak:8080
  - service: http_status:404
