apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-conf
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-userdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-addons
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
