apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openhab
  labels:
    release: kubernetes-monitoring
spec:
  selector:
    matchLabels:
      app: openhab
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 30s
